### ISSUE TITLE
选择河北省的时候它下面的市无法滑动

### ISSUE THREAD

**Issue by miuqiang** [ydcss/ydui-district#1]
![screenshot_20170913-171423](https://user-images.githubusercontent.com/19277011/30369491-482dd6d0-98a7-11e7-8d7e-e8d7bfbd1641.png)

在谷歌模拟器里正常，在华为meta8 和苹果手机里均无法滑动

**Comment by ydcss** [comment]
这个样式不太对劲啊。用的是那个版本的ydui呀？另外去vue-ydui项目提issues吧。

**Comment by miuqiang** [comment]
好像是因为我没有导入重置的样式的原因造成的
