### ISSUE TITLE
关于部分市区数据的问题

### ISSUE THREAD

**Issue by weixisheng** [ydcss/ydui-district#2]
## 1、引用的是 gov_province_city_area_id.js，例如选择了【广东 广州市 越秀区】
![qq 20171019154254](https://user-images.githubusercontent.com/16042305/31759603-7e5b202e-b4e4-11e7-8be3-bec65a5864bb.png)
## 2、想要修改所在地信息，例如中山市，由于没有区数据，默认选了之前的【越秀区】
![qq 20171019154228](https://user-images.githubusercontent.com/16042305/31759701-d5ff55f2-b4e4-11e7-9594-90e2c01f7eff.png)
## 3、当然了，引用京东版数据，是没问题的，只是区域字段id跟后台不匹配
![qq 20171019155157](https://user-images.githubusercontent.com/16042305/31759911-78eb02b6-b4e5-11e7-9d3a-c70bcbee4dde.png)

**Comment by ydcss** [comment]
![qq 20171019165313](https://user-images.githubusercontent.com/5517400/31762535-1f5d603c-b4ee-11e7-885e-6365ba21720e.png)
确实是，国家统计局的数据不完整(/ □ \\)。
另外一个组件确实也存在缺陷，假设选择的项没有子集，应该清除之前的选择，下次更新修复。

关于统计局数据不完整，我想想看有什么办法。若你有好的建议欢迎分享。

**Comment by weixisheng** [comment]
一般是第二级的数据可能没有子集，我现在就暂时针对这种情况做个判断。
```javascript
 result1(res) {
      this.proviceId = res.itemValue1;
      this.cityId = res.itemValue2;
      if (res.itemValue3) {
        this.areaId = res.itemValue3;
        this.adddressName = `${res.itemName1},${res.itemName2},${res.itemName3}`;
      } else {
        this.areaId='';
        this.adddressName = `${res.itemName1},${res.itemName2},`;
      }
    },
```
不过，如果不影响其他功能，可以清除之前的选择；或者直接给一些没有子集的选择项，赋值初始字段
```javascript
{"v":"xx","n":"市辖区"}
```
_感谢百忙之中抽空查看哈~_

**Comment by ydcss** [comment]
你好，组件ydui-cityselect已修复没有子集错误的逻辑。数据源也相应添加遗漏的数据。

**Comment by weixisheng** [comment]
好的。
